INSERT INTO Tipos_Usuarios  values('s'),('a'),('n')

INSERT INTO Cargos_Junta_Directiva(nombre_cargo) values ('Presidente'),('Vicepresidente'),
														('Tesorero'),('Secretario'),('Vocal'),
														('Fiscal')

INSERT INTO Administradores (codigo_cargo_junta_directiva) values (1),(2),(3),(4),(5),(6)


INSERT INTO Usuarios (nombre_usuario,contrasena,codigo_tipo_usuario,codigo_administrador,fecha_ingreso)
					values ('admin1@tec.ac.r','password','a',1,GETDATE()),
							('admin2@tec.ac.r','password','a',2,GETDATE()),
							('admin3@tec.ac.r','password','a',3,GETDATE()),
							('admin4@tec.ac.r','password','a',4,GETDATE()),
							('admin5@tec.ac.r','password','a',5,GETDATE()),
							('admin6@tec.ac.r','password','a',6,GETDATE())

INSERT INTO Usuarios (nombre_usuario,contrasena,codigo_tipo_usuario,fecha_ingreso)
					values ('usuario1@tec.ac.r','password','n',GETDATE())


INSERT INTO Usuarios (nombre_usuario,contrasena,codigo_tipo_usuario,fecha_ingreso) values
('usuario2@tec.ac.r','password2','n',GETDATE()),
('usuario3@tec.ac.r','password3','n',GETDATE()),
('usuario4@tec.ac.r','password4','n',GETDATE()),
('usuario5@tec.ac.r','password5','n',GETDATE()),
('usuario6@tec.ac.r','password6','n',GETDATE()),
('usuario7@tec.ac.r','password7','n',GETDATE()),
('usuario8@tec.ac.r','password8','n',GETDATE()),
('usuario9@tec.ac.r','password9','n',GETDATE()),
('usuario10@tec.ac.r','password10','n',GETDATE()),
('usuario11@tec.ac.r','password11','n',GETDATE()),
('usuario12@tec.ac.r','password12','n',GETDATE()),
('usuario13@tec.ac.r','password13','n',GETDATE()),
('usuario14@tec.ac.r','password14','n',GETDATE()),
('usuario15@tec.ac.r','password15','n',GETDATE()),
('usuario16@tec.ac.r','password16','n',GETDATE()),
('usuario17@tec.ac.r','password17','n',GETDATE()),
('usuario18@tec.ac.r','password18','n',GETDATE()),
('usuario19@tec.ac.r','password19','n',GETDATE()),
('usuario20@tec.ac.r','password20','n',GETDATE()),
('usuario21@tec.ac.r','password21','n',GETDATE()),
('usuario22@tec.ac.r','password22','n',GETDATE()),
('usuario23@tec.ac.r','password23','n',GETDATE()),
('usuario24@tec.ac.r','password24','n',GETDATE()),
('usuario25@tec.ac.r','password25','n',GETDATE()),
('usuario26@tec.ac.r','password26','n',GETDATE()),
('usuario27@tec.ac.r','password27','n',GETDATE()),
('usuario28@tec.ac.r','password28','n',GETDATE()),
('usuario29@tec.ac.r','password29','n',GETDATE()),
('usuario30@tec.ac.r','password30','n',GETDATE()),
('usuario31@tec.ac.r','password31','n',GETDATE()),
('usuario32@tec.ac.r','password32','n',GETDATE()),
('usuario33@tec.ac.r','password33','n',GETDATE()),
('usuario34@tec.ac.r','password34','n',GETDATE()),
('usuario35@tec.ac.r','password35','n',GETDATE()),
('usuario36@tec.ac.r','password36','n',GETDATE()),
('usuario37@tec.ac.r','password37','n',GETDATE()),
('usuario38@tec.ac.r','password38','n',GETDATE()),
('usuario39@tec.ac.r','password39','n',GETDATE()),
('usuario40@tec.ac.r','password40','n',GETDATE()),
('usuario41@tec.ac.r','password41','n',GETDATE()),
('usuario42@tec.ac.r','password42','n',GETDATE()),
('usuario43@tec.ac.r','password43','n',GETDATE()),
('usuario44@tec.ac.r','password44','n',GETDATE()),
('usuario45@tec.ac.r','password45','n',GETDATE()),
('usuario46@tec.ac.r','password46','n',GETDATE()),
('usuario47@tec.ac.r','password47','n',GETDATE()),
('usuario48@tec.ac.r','password48','n',GETDATE()),
('usuario49@tec.ac.r','password49','n',GETDATE())


Insert into Tallas_Camisas values ('xxs'),('xs'),('s'),('m'),('l'),('xl'),('xxl'),('xxxl')

Insert into Provincias (nombre_provincia) values  ('San José'),('Alajuela'),('Cartago'),('Heredia'),
												  ('Guanacaste'),('Puntarenas'),('Limon')

Insert into Sedes (nombre_sede) values ('Cartago'),('San Carlos'),('Alajuela'),('San José'),('Limon')


INSERT INTO Cantones (codigo_provincia,nombre_canton) values
(1,'SAN JOSÉ'),
(1,'PÉREZ ZELEDÓN'),
(1,'ESCAZÚ'),
(1,'DESAMPARADOS'),
(1,'PURISCAL'),
(1,'TARRAZÚ'),
(1,'ASERRÍ'),
(1,'MORA'),
(1,'GOICOECHEA'),
(1,'SANTA ANA'),
(1,'ALAJUELITA'),
(1,'VÁZQUEZ DE CORONADO'),
(1,'ACOSTA'),
(1,'TIBÁS'),
(1,'MORAVIA'),
(1,'MONTES DE OCA'),
(1,'TURRUBARES'),
(1,'DOTA'),
(1,'CURRIDABAT'),
(1,'LEÓN CORTÉS CASTRO'),
(2,'ALAJUELA'),
(2,'SAN CARLOS'),
(2,'UPALA'),
(2,'LOS CHILES'),
(2,'GUATUSO'),
(2,'SAN MATEO'),
(2,'OROTINA'),
(2,'SAN RAMÓN'),
(2,'GRECIA'),
(2,'ATENAS'),
(2,'NARANJO'),
(2,'PALMARES'),
(2,'POÁS'),
(2,'ZARCERO'),
(2,'VALVERDE VEGA'),
(3,'CARTAGO'),
(3,'PARAÍSO'),
(3,'LA UNIÓN'),
(3,'JIMÉNEZ'),
(3,'TURRIALBA'),
(3,'ALVARADO'),
(3,'OREAMUNO'),
(3,'EL GUARCO'),
(4,'HEREDIA'),
(4,'SARAPIQUÍ'),
(4,'BARVA'),
(4,'SANTO DOMINGO'),
(4,'SANTA BÁRBARA'),
(4,'SAN RAFAEL'),
(4,'SAN ISIDRO'),
(4,'BELÉN'),
(4,'FLORES'),
(4,'SAN PABLO'),
(5,'LIBERIA'),
(5,'NICOYA'),
(5,'SANTA CRUZ'),
(5,'BAGACES'),
(5,'CARRILLO'),
(5,'CAÑAS'),
(5,'ABANGARES'),
(5,'TILARÁN'),
(5,'NANDAYURE'),
(5,'LA CRUZ'),
(5,'HOJANCHA'),
(6,'PUNTARENAS'),
(6,'ESPARZA'),
(6,'MONTES DE ORO'),
(6,'AGUIRRE'),
(6,'PARRITA'),
(6,'GARABITO'),
(6,'BUENOS AIRES'),
(6,'OSA'),
(6,'GOLFITO'),
(6,'COTO BRUS'),
(6,'CORREDORES'),
(7,'LIMÓN'),
(7,'POCOCÍ'),
(7,'SIQUIRRES'),
(7,'TALAMANCA'),
(7,'MATINA'),
(7,'GUÁCIMO')

insert into Departamentos (nombre_departamento) values 
('GOBIERNO INSTITUCIONAL'),
('VICERRECTORÍA DE ADMINISTRACIÓN'),
('VICERRECTORÍA DE DOCENCIA'),
('VICERRECTORÍA DE INVESTIGACIÓN Y EXTENSIÓN (VIE)'),
('VICERRECTORÍA DE VIDA ESTUDIANTIL Y SERVICIOS ACADÉMICOS (VIESA)'),
('OFICINAS Y OTROS')

INSERT INTO Hobbies (descripcion_hobby) values 
('Aviones Spotting '),
('Aerografía '),
('Actuacion'),
('Aeromodelismo '),
('Amateur de Astronomía '),
('Radioaficionados '),
('Animales / Mascotas / Perros '),
('Artes '),
('Astrología '),
('Astronomía '),
('Backgammon (juego de mesa)'),
('Bádminton (deporte de raqueta)'),
('Béisbol '),
('Baloncesto '),
('Playa / Tomar el sol '),
('Caminar por la playa '),
('Chaquira (manualidad con collares)'),
('Beatboxing (imitar sonidos por la boca)'),
('Convertirse en un niño Abogado '),
('Tocar campanas'),
('Danza del vientre '),
('Andar en bicicleta '),
('Observación de aves '),
('Filigran (doblar papel o alambre)'),
('Acrobacias con bicicletas (BMX)'),
('Herrería '),
('Blogging '),
('Juegos de mesa '),
('Canotaje '),
('Disfraces'),
('Bonsai (Arbol con piedrecitas)'),
('Bolos '),
('Mezcla de la cerveza '),
('Puente '),
('Llevar comida a la movilidad reducida '),
('Construcción de Muñecas '),
('Observador de mariposas '),
('Colección de botones'),
('Caligrafía '),
('Escribir poemas o cuentos cortos'),
('Campamento '),
('Hacer vela '),
('Piragüismo  o canotaje'),
('Car Racing '),
('Casino (Apuestas) '),
('Buceo en Cuevas '),
('Cheerleading '),
('Ajedrez '),
('Iglesia / actividades de la iglesia '),
('Fumar cigarros '),
('Mirar nubes'),
('Coleccionar monedas, postales'),
('Coleccionar '),
('Coleccionar antigüedades '),
('Recopilación de ilustraciones '),
('Componer música '),
('Actividades Informáticas '),
('Cocina '),
('Cosplay '),
('Artesanías '),
('Bricolaje o trabajar con madera'),
('Croché '),
('Ganchillo '),
('Punto de cruz '),
('Crucigramas '),
('Baile '),
('Dardos '),
('Reciclaje'),
('Fotografía Digital '),
('Muñecas '),
('Dominó '),
('Dibujo '),
('Buceo '),
('Comer fuera '),
('Cursos '),
('Electrónica '),
('Bordado '),
('Entrevistar a gente en la calle'),
('Ejercicio (aeróbic, pesas) '),
('Coches rápidos '),
('Esgrima '),
('Pesca '),
('Fútbol '),
('Maquillaje artistico'),
('Acuarios'),
('Frisbee Golf - Frolf '),
('Juegos  de cartas'),
('Jardinería '),
('Venta de Garage'),
('Genealogía '),
('Geocaching '),
('La caza del fantasma '),
('Glowsticking '),
('Ir al cine '),
('Golf '),
('Ir Racing Kart '),
('Hacer una pelicula casera'),
('Guitarra '),
('Análisis de escritura a mano '),
('Ser boyscout'),
('Excursionismo '),
('Vender jugos o pasteles'),
('Reparación '),
('Ir a cine'),
('Paseos a caballo '),
('Globo de aire caliente '),
('Hula hoop o hula hula'),
('Caza '),
('Ilusión optica'),
('Internet '),
('Los motores a reacción '),
('Fabricación de Joyas '),
('Rompecabezas '),
('Malabarismo '),
('Llevar un diario '),
('Cocina Química '),
('Cometas '),
('Volar cometas'),
('Tejido '),
('Bordado'),
('Láser '),
('Lanzar Dardos'),
('Aprende a jugar al poker '),
('Aprender un idioma '),
('Aprender un instrumento '),
('Aprender a pilotar un avión '),
('Legos '),
('Escuchando la música '),
('Macramé '),
('Magia '),
('Hacer Model Cars '),
('Modelado con cerillas o topitos de algodon'),
('Meditación '),
('Microscopía '),
('Metal que detecta  movimiento'),
('Modelado de cohetes'),
('Modelado de los buques '),
('Modelos '),
('Motocicletas '),
('Ciclismo de Montaña '),
('Montañismo '),
('Instrumentos Musicales '),
('Bordados '),
('Ser propietario de un coche antiguo '),
('Origami '),
('Pintura '),
('Paintball '),
('Fabricación de papel '),
('Papermache '),
('Paracaidismo '),
('Observar a la gente '),
('Fotografía '),
('Piano '),
('Pinochle '),
('Reproducción de música '),
('Jugar deportes de equipo '),
('Cerámica '),
('Títeres '),
('Pirotécnica '),
('Acolchado '),
('Rafting '),
('Fan de los trenes y carriles'),
('R / C Barcos '),
('R / C Coches '),
('R / C Helicópteros '),
('R / C Aviones '),
('Lectura '),
('Lectura a las personas mayores '),
('Relajarte '),
('El alquiler de películas '),
('El rescate de animales maltratados o abandonados '),
('Robótica '),
('Recopilación de Rock '),
('Rockets '),
('Conocer Funcionamiento de las cosas'),
('Acuarios de agua salada o dulce'),
('De Scrapbooking '),
('Buceo '),
('Coser '),
('Pesca del tiburón '),
('Tiro al aire'),
('Compras '),
('Cantar en el coro '),
('Skateboarding '),
('Dibujar '),
('Paracaidismo '),
('Sueño '),
('Pipas '),
('Snorkel '),
('Fabricación de Jabón o velas'),
('Fútbol '),
('Socializar con los amigos / vecinos '),
('Pintura digital'),
('Pasar tiempo con la familia / hijos '),
('Filatelia o coleccion de sobre y sellos'),
('Narración de Cuentos '),
('Hacer nudos cuerdas '),
('Surf Pesca '),
('Natación '),
('Degustación de té '),
('Tenis '),
('Bobinas de Tesla '),
('Tetris '),
('Los mensajes de texto '),
('Textiles '),
('Frotamiento de Lápida'),
('Herramienta de Recolección '),
('Recogida de juguetes '),
('Recolección de basura'),
('Crear un negocio'),
('Arreglar computadores a domicilio'),
('Ir de viaje '),
('La caza del tesoro '),
('Trekkie '),
('Tutoría para niños '),
('Ver la televisión '),
('Crear un videojuego'),
('Video Juegos '),
('Voluntario '),
('Ir a pie  por toda la cuidad'),
('Leer o inventar historias de fantasia'),
('Mirar los acontecimientos deportivos '),
('Windsurf '),
('Vinificación '),
('Trabajos en madera '),
('Trabajo en una despensa de alimentos '),
('Trabajo en los coches '),
('Escritura '),
('Yoga '),
('YoYo'),
('Polcelanicron o porcelana fria')

insert into Sub_Departamentos (codigo_departamento, nombre_sub_departamento) values 
 (1, 'Asamblea Institucional Representativa (AIR)'),
 (1, 'Consejo Institucional'),
 (1, 'Rectoría'),
 (1, 'Federación de Estudiantes del TEC (FEITEC)'),
 (2, 'Departamento de Recursos Humanos'),
 (2, 'Departamento Financiero Contable'),
 (2, 'Departamento de Aprovisionamiento'),
 (2, 'Departamento de Servicios Generales'),
 (2, 'Departamento de Administración de Mantenimiento'),
 (3, 'Escuela de Administración de Empresas'),
 (3, 'Escuela de Ingeniería en Computación'),
 (3, 'Escuela de Ingeniería en Electrónica'),
 (3, 'Escuela de Ingeniería en Producción Industrial'),
 (3, 'Área Académica Agroforestal'),
 (3, 'Escuela de Ingeniería en Electromecánica'),
 (3, 'Escuela de Ingeniería en Construcción'),
 (3, 'Escuela de Ingeniería en Diseño Industrial'),
 (3, 'Escuela de Educación Técnica'),
 (3, 'Escuela de Ingeniería en Seguridad Laboral e Higiene Ambiental'),
 (3, 'Escuela de Arquitectura y Urbanismo'),
 (3, 'Escuela de Ciencia e Ingeniería de los Materiales'),
 (3, 'Escuela de Biología'),
 (3, 'Escuela de Matemática'),
 (3, 'Escuela de Ingeniería Forestal'),
 (3, 'Escuela de Química'),
 (3, 'Área de Ingeniería Mecatrónica'),
 (3, 'Área Maestría en Gerencia de Proyectos'),
 (3, 'Escuela de Ingeniería Agrícola'),
 (3, 'Escuela de Ingeniería Agropecuaria Administrativa'),
 (3, 'Escuela de Ciencias Sociales'),
 (3, 'Escuela de Ciencias del Lenguaje'),
 (3, 'Escuela de Física'),
 (3, 'Centro de Desarrollo Académico'),
 (3, 'Área de Ingeniería en Computadores'),
 (3, 'tecDigital'),
 (4, 'Dirección de Proyectos'),
 (4, 'Dirección de Cooperación'),
 (4, 'Centro de Vinculación Universidad Empresa'),
 (4, 'Editorial Tecnológica'),
 (5, 'Escuela de Cultura y Deporte'),
 (5, 'Departamento de Admisión y Registro'),
 (5, 'Departamento de Servicios Bibliotecarios'),
 (5, 'Departamento de Trabajo Social y Salud'),
 (5, 'Departamento de Orientación y Psicología'),
 (6, 'Tribunal Institucional Electoral (TIE)'),
 (6, 'Auditoría Interna'),
 (6, 'Oficina de Planificación Institucional (OPI)'),
 (6, 'Oficina de Asesoría Legal'),
 (6, 'Oficina de Comunicación y Mercadeo'),
 (6, 'Oficina de Ingeniería'),
 (6, 'Departamento de Administración de Tecnologías de Información y Comunicaciones (DATIC)'),
 (6, 'Oficina de Equidad de Género'),
 (6, 'Sistema de Gestión Ambiental TEC')



insert into grados_academicos (nivel_especializacion, campo_estudio) values
('Bach.','Administración de Empresas'),
('Bach.','Administración de Tecnologías de Información'),
('Bach.','Educación Técnica'),
('Bach.','Enseñanza de la Matemática asistida por computadora'),
('Bach.','Gestión en Turismo Sostenible'),
('Bach.','Ingeniería Agrícola'),
('Bach.','Ingeniería Agronegocios'),
('Bach.','Ingeniería Ambiental'),
('Bach.','Ingeniería en Biotecnología'),
('Bach.','Ingeniería en Computación'),
('Bach.','Ingeniería en Computadores'),
('Bach.','Ingeniería en Construcción'),
('Bach.','Ingeniería en Diseño Industrial'),
('Bach.','Ingeniería en Electrónica'),
('Bach.','Ingeniería en Mantenimiento Industrial'),
('Bach.','Ingeniería en Materiales'),
('Bach.','Ingeniería en Producción de Industrial')

Insert into grupos (descripcion_grupo) values
('Todos'),
('Padres y Madres'),
('Sede Cartago')

Insert into miembros_grupo (codigo_usuario,codigo_grupo) values
(20, 3),(21, 3),(22, 3),(23, 3),(24, 3),(25, 3),(26, 3),(27, 3),(28, 3),(29, 3),
(30, 3),(31, 3),(32, 3),(33, 3),(34, 3),(35, 3),(36, 3),(37, 3),(38, 3),(39, 3),
(30, 2),(31, 2),(32, 2),(33, 2),(34, 2),(35, 2),(36, 2),(37, 2),(38, 2),(39, 2),
(1, 1),(2, 1),(3, 1),(4, 1),(5, 1),(6, 1),(7, 1),(8, 1),(9, 1),(10, 1),(11, 1),(12, 1),(13, 1),(14, 1),(15, 1),
(16, 1),(17, 1),(18, 1),(19, 1),(20, 1),(21, 1),(22, 1),(23, 1),(24, 1),(25, 1),(26, 1),(27, 1),(28, 1),(29, 1),
(30, 1),(31, 1),(32, 1),(33, 1),(34, 1),(35, 1),(36, 1),(37, 1),(38, 1),(39, 1),(40, 1),(41, 1),(42, 1),(43, 1),
(44, 1),(45, 1),(46, 1),(47, 1),(48, 1),(49, 1),(50, 1),(51, 1),(52, 1),(53, 1),(54, 1),(55, 1)




INSERT INTO INFORMACION_PERSONAS(nombre,apellidos,fecha_nacimiento,correo_personal,codigo_talla_camisa,cargo_jefatura,vegetariano,codigo_sede,codigo_canton,codigo_sub_departamento,cedula,correo_institucional,telefono_trabajo,numero_extension) values
('Daniel','Panigua',GETDATE(),'Daniel@correo.com','xxl',0,1,2,12,13,406574154,'DanielPanigua@tec.ac.cr','66738962',264),
('Julio','Vargas',GETDATE(),'Julio@correo.com','xl',1,1,3,52,22,360885273,'JulioVargas@tec.ac.cr','77942773',567),
('Karina','Rodriguez',GETDATE(),'Karina@correo.com','xs',0,0,5,17,29,560171664,'KarinaRodriguez@tec.ac.cr','96262466',939),
('Paula','Panigua',GETDATE(),'Paula@correo.com','xs',0,1,1,28,18,769777096,'PaulaPanigua@tec.ac.cr','82690887',317),
('Luis Carlos','Carmona',GETDATE(),'Luis Carlos@correo.com','l',1,0,3,74,13,235164816,'Luis CarlosCarmona@tec.ac.cr','17872929',404),
('Karina','Vargas',GETDATE(),'Karina@correo.com','l',0,0,3,69,29,239271283,'KarinaVargas@tec.ac.cr','77601199',426),
('David','Carmona',GETDATE(),'David@correo.com','m',0,0,3,6,28,718664896,'DavidCarmona@tec.ac.cr','31771082',193),
('Cristian','Viquez',GETDATE(),'Cristian@correo.com','xl',1,0,5,16,21,164567386,'CristianViquez@tec.ac.cr','48205285',462),
('Johanna','Pereira',GETDATE(),'Johanna@correo.com','xxl',1,1,3,17,20,170227959,'JohannaPereira@tec.ac.cr','40778737',437),
('Sebastian','Cruz',GETDATE(),'Sebastian@correo.com','l',0,0,5,47,30,573902304,'SebastianCruz@tec.ac.cr','26952022',292),
('Valery','Vargas',GETDATE(),'Valery@correo.com','l',0,1,1,29,47,787670445,'ValeryVargas@tec.ac.cr','53801974',108),
('Johanna','Murillo',GETDATE(),'Johanna@correo.com','l',1,0,5,39,33,123079373,'JohannaMurillo@tec.ac.cr','48097017',442),
('Gilberto','Pacheco',GETDATE(),'Gilberto@correo.com','xs',1,1,4,45,11,187722735,'GilbertoPacheco@tec.ac.cr','41934681',314),
('Karina','Murillo',GETDATE(),'Karina@correo.com','xxl',1,0,1,41,6,145399594,'KarinaMurillo@tec.ac.cr','77071301',609),
('Heiner','Pacheco',GETDATE(),'Heiner@correo.com','xxs',0,0,1,75,8,218144083,'HeinerPacheco@tec.ac.cr','13577420',403),
('Karina','Pacheco',GETDATE(),'Karina@correo.com','xl',0,0,4,79,6,239622172,'KarinaPacheco@tec.ac.cr','40221158',929),
('Heiner','Pacheco',GETDATE(),'Heiner@correo.com','xs',0,1,2,13,17,153369341,'HeinerPacheco@tec.ac.cr','28774452',661),
('Valery','Carmona',GETDATE(),'Valery@correo.com','xxl',1,0,2,45,33,636305085,'ValeryCarmona@tec.ac.cr','83560686',377),
('Paula','Viquez',GETDATE(),'Paula@correo.com','l',0,0,1,38,26,119944606,'PaulaViquez@tec.ac.cr','17327665',603),
('Sebastian','Panigua',GETDATE(),'Sebastian@correo.com','s',1,1,2,33,13,519909680,'SebastianPanigua@tec.ac.cr','63971938',110),
('Rebeca','Rodriguez',GETDATE(),'Rebeca@correo.com','l',0,1,1,34,20,478267626,'RebecaRodriguez@tec.ac.cr','25079859',718),
('Sofia','Jimenez',GETDATE(),'Sofia@correo.com','xxs',1,1,1,75,6,419614766,'SofiaJimenez@tec.ac.cr','70137175',836),
('Sofia','Jimenez',GETDATE(),'Sofia@correo.com','xxl',1,1,4,61,36,615653393,'SofiaJimenez@tec.ac.cr','61019359',394),
('David','Cruz',GETDATE(),'David@correo.com','xxs',1,0,2,9,42,779180298,'DavidCruz@tec.ac.cr','18804300',840),
('Heiner','Obando',GETDATE(),'Heiner@correo.com','xxs',1,1,1,8,43,305060268,'HeinerObando@tec.ac.cr','15141579',128),
('Paula','Murillo',GETDATE(),'Paula@correo.com','xxs',0,1,1,56,27,413803461,'PaulaMurillo@tec.ac.cr','88106485',689),
('Sofia','Pacheco',GETDATE(),'Sofia@correo.com','xl',1,1,5,45,1,407653518,'SofiaPacheco@tec.ac.cr','00936588',713),
('Daniel','Viquez',GETDATE(),'Daniel@correo.com','m',1,1,3,52,34,513829525,'DanielViquez@tec.ac.cr','86577805',883),
('Cristian','Cruz',GETDATE(),'Cristian@correo.com','xl',0,0,5,25,51,690112631,'CristianCruz@tec.ac.cr','92709500',774),
('Gilberto','Murillo',GETDATE(),'Gilberto@correo.com','m',1,0,1,77,45,477030694,'GilbertoMurillo@tec.ac.cr','31642830',794),
('Karina','Rodriguez',GETDATE(),'Karina@correo.com','l',1,1,4,79,38,163951598,'KarinaRodriguez@tec.ac.cr','42776610',491),
('Paula','Jimenez',GETDATE(),'Paula@correo.com','m',0,1,5,13,31,482138296,'PaulaJimenez@tec.ac.cr','99737374',220),
('David','Panigua',GETDATE(),'David@correo.com','xxl',0,1,2,66,2,274407247,'DavidPanigua@tec.ac.cr','38745905',208),
('Johanna','Obando',GETDATE(),'Johanna@correo.com','xxl',1,1,1,13,28,625183072,'JohannaObando@tec.ac.cr','51822896',105),
('Julio','Vargas',GETDATE(),'Julio@correo.com','xxs',1,1,4,11,8,232982436,'JulioVargas@tec.ac.cr','20828086',894),
('Daniel','Pereira',GETDATE(),'Daniel@correo.com','xl',1,0,1,66,15,420099852,'DanielPereira@tec.ac.cr','70600623',312),
('Karina','Viquez',GETDATE(),'Karina@correo.com','xxs',1,1,1,18,23,392077573,'KarinaViquez@tec.ac.cr','34467001',458),
('Cristian','Obando',GETDATE(),'Cristian@correo.com','xs',1,1,5,42,45,215189187,'CristianObando@tec.ac.cr','65777813',890),
('Luis Carlos','Panigua',GETDATE(),'Luis Carlos@correo.com','s',1,0,1,20,38,131687013,'Luis CarlosPanigua@tec.ac.cr','70451798',417),
('Daniel','Cruz',GETDATE(),'Daniel@correo.com','m',1,0,5,4,23,565723260,'DanielCruz@tec.ac.cr','48359300',168),
('Valery','Pereira',GETDATE(),'Valery@correo.com','s',1,0,5,70,36,788862263,'ValeryPereira@tec.ac.cr','99823949',929),
('Cristian','Murillo',GETDATE(),'Cristian@correo.com','xxl',0,0,3,72,24,533355289,'CristianMurillo@tec.ac.cr','34803227',810),
('Paula','Rodriguez',GETDATE(),'Paula@correo.com','xxl',1,0,1,33,37,521631526,'PaulaRodriguez@tec.ac.cr','77780723',157),
('Gilberto','Pereira',GETDATE(),'Gilberto@correo.com','xxl',0,0,1,80,46,354078232,'GilbertoPereira@tec.ac.cr','87150960',682),
('Johanna','Vargas',GETDATE(),'Johanna@correo.com','l',1,1,5,5,36,777264707,'JohannaVargas@tec.ac.cr','28920902',296),
('Sebastian','Obando',GETDATE(),'Sebastian@correo.com','xl',1,1,2,78,30,213877030,'SebastianObando@tec.ac.cr','27104193',680),
('Paula','Cruz',GETDATE(),'Paula@correo.com','xxl',1,0,5,53,19,231403838,'PaulaCruz@tec.ac.cr','54036478',173),
('Cristian','Jimenez',GETDATE(),'Cristian@correo.com','s',0,0,1,41,21,514587843,'CristianJimenez@tec.ac.cr','03555641',272),
('Paula','Carmona',GETDATE(),'Paula@correo.com','l',1,1,3,76,8,100772164,'PaulaCarmona@tec.ac.cr','00590916',412),
('Cristian','Carmona',GETDATE(),'Cristian@correo.com','m',0,1,5,60,45,263972593,'CristianCarmona@tec.ac.cr','98033598',459),
('Sofia','Murillo',GETDATE(),'Sofia@correo.com','xxl',0,1,3,67,5,565720535,'SofiaMurillo@tec.ac.cr','28449426',918),
('Karina','Viquez',GETDATE(),'Karina@correo.com','s',1,1,4,42,27,469387151,'KarinaViquez@tec.ac.cr','57243596',251),
('Fabian','Obando',GETDATE(),'Fabian@correo.com','l',1,0,2,2,39,249418713,'FabianObando@tec.ac.cr','07172150',169),
('Heiner','Pereira',GETDATE(),'Heiner@correo.com','l',1,1,4,63,46,578906388,'HeinerPereira@tec.ac.cr','69425466',522),
('Heiner','Pacheco',GETDATE(),'Heiner@correo.com','xxl',0,0,4,49,10,692592000,'HeinerPacheco@tec.ac.cr','94090941',700)

UPDATE Usuarios
Set codigo_informacion_persona = codigo_usuario




Insert Into Grados_Academicos_Personas (codigo_grado_academico,codigo_informacion_persona) Values
(1,1),(2,1),(3,1),(4,1),(10,2),(10,3),(12,3)

insert into Tipos_Eventos (descripcion) values('Evento de Caridad')
insert into Tipos_Eventos (descripcion) values('Paseo')
insert into Tipos_Eventos (descripcion) values('Charla')
insert into Tipos_Eventos (descripcion) values('Competencia')
